// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EuNet.CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using EuNet.Core;
using EuNet.Rpc;
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_ANDROID || UNITY_IOS
using EuNet.Unity;
using UnityEngine;
#endif
using Rpc.Test.Interface;

#region Rpc.Test.Interface.IGreeterRpc

namespace Rpc.Test.Interface
{
    public interface IGreeterRpc_NoReply
    {
        void Greet(string name);
        void GreetClass(Rpc.Test.Interface.DataClass dataClass);
        void GreetInterfaceSerializeClass(Rpc.Test.Interface.InterfaceSerializeClass dataClass);
        void SessionParameter(EuNet.Core.ISession session);
    }

    public enum IGreeterRpc_Enum : int
    {
        Greet = -567773818,
        GreetClass = -1772909904,
        GreetInterfaceSerializeClass = -258043401,
        SessionParameter = -1629016744,
    }

    public class GreeterRpc : RpcRequester, IGreeterRpc, IGreeterRpc_NoReply
    {
        public override Type InterfaceType => typeof(IGreeterRpc);

        public GreeterRpc() : base(null)
        {
        }

        public GreeterRpc(ISession target) : base(target)
        {
        }

        public GreeterRpc(ISession target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IGreeterRpc_NoReply WithNoReply()
        {
            return this;
        }

        public GreeterRpc WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GreeterRpc(Target, requestWaiter, Timeout);
        }

        public GreeterRpc WithTimeout(TimeSpan? timeout)
        {
            return new GreeterRpc(Target, RequestWaiter, timeout);
        }

        public async Task<string> Greet(string name)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.Greet);
                _writer_.Write(name);
                using(var _reader_ = await SendRequestAndReceive(_writer_))
                {
                    return _reader_.ReadString();
                }
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        public async Task<Rpc.Test.Interface.DataClass> GreetClass(Rpc.Test.Interface.DataClass dataClass)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.GreetClass);
                NetDataSerializer.Serialize<Rpc.Test.Interface.DataClass>(_writer_, dataClass);
                using(var _reader_ = await SendRequestAndReceive(_writer_))
                {
                    return NetDataSerializer.Deserialize<Rpc.Test.Interface.DataClass>(_reader_);
                }
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        public async Task<Rpc.Test.Interface.InterfaceSerializeClass> GreetInterfaceSerializeClass(Rpc.Test.Interface.InterfaceSerializeClass dataClass)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.GreetInterfaceSerializeClass);
                _writer_.Write<Rpc.Test.Interface.InterfaceSerializeClass>(dataClass);
                using(var _reader_ = await SendRequestAndReceive(_writer_))
                {
                    return _reader_.Read<Rpc.Test.Interface.InterfaceSerializeClass>();
                }
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        public async Task<string> SessionParameter(EuNet.Core.ISession session)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.SessionParameter);
                
                using(var _reader_ = await SendRequestAndReceive(_writer_))
                {
                    return _reader_.ReadString();
                }
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void IGreeterRpc_NoReply.Greet(string name)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.Greet);
                _writer_.Write(name);
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void IGreeterRpc_NoReply.GreetClass(Rpc.Test.Interface.DataClass dataClass)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.GreetClass);
                NetDataSerializer.Serialize<Rpc.Test.Interface.DataClass>(_writer_, dataClass);
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void IGreeterRpc_NoReply.GreetInterfaceSerializeClass(Rpc.Test.Interface.InterfaceSerializeClass dataClass)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.GreetInterfaceSerializeClass);
                _writer_.Write<Rpc.Test.Interface.InterfaceSerializeClass>(dataClass);
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void IGreeterRpc_NoReply.SessionParameter(EuNet.Core.ISession session)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterRpc_Enum.SessionParameter);
                
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }
    }

    public abstract class GreeterRpcServiceAbstract : IRpcInvokable, IGreeterRpc
    {
        public abstract Task<string> Greet(string name);
        public abstract Task<Rpc.Test.Interface.DataClass> GreetClass(Rpc.Test.Interface.DataClass dataClass);
        public abstract Task<Rpc.Test.Interface.InterfaceSerializeClass> GreetInterfaceSerializeClass(Rpc.Test.Interface.InterfaceSerializeClass dataClass);
        public abstract Task<string> SessionParameter(EuNet.Core.ISession session);
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            ISession session = _target_ as ISession;
            var typeEnum = (IGreeterRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case IGreeterRpc_Enum.Greet:
                    {
                        var name = _reader_.ReadString();
                        var _result_ = await Greet(name);
                        _writer_.Write(_result_);
                    }
                    break;
                case IGreeterRpc_Enum.GreetClass:
                    {
                        var dataClass = NetDataSerializer.Deserialize<Rpc.Test.Interface.DataClass>(_reader_);
                        var _result_ = await GreetClass(dataClass);
                        NetDataSerializer.Serialize<Rpc.Test.Interface.DataClass>(_writer_, _result_);
                    }
                    break;
                case IGreeterRpc_Enum.GreetInterfaceSerializeClass:
                    {
                        var dataClass = _reader_.Read<Rpc.Test.Interface.InterfaceSerializeClass>();
                        var _result_ = await GreetInterfaceSerializeClass(dataClass);
                        _writer_.Write<Rpc.Test.Interface.InterfaceSerializeClass>(_result_);
                    }
                    break;
                case IGreeterRpc_Enum.SessionParameter:
                    {
                        
                        var _result_ = await SessionParameter(session);
                        _writer_.Write(_result_);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }

    public class GreeterRpcServiceSession : IRpcInvokable
    {
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            ISession session = _target_ as ISession;
            var typeEnum = (IGreeterRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case IGreeterRpc_Enum.Greet:
                    {
                        var name = _reader_.ReadString();
                        var _result_ = await (session as IGreeterRpc).Greet(name);
                        _writer_.Write(_result_);
                    }
                    break;
                case IGreeterRpc_Enum.GreetClass:
                    {
                        var dataClass = NetDataSerializer.Deserialize<Rpc.Test.Interface.DataClass>(_reader_);
                        var _result_ = await (session as IGreeterRpc).GreetClass(dataClass);
                        NetDataSerializer.Serialize<Rpc.Test.Interface.DataClass>(_writer_, _result_);
                    }
                    break;
                case IGreeterRpc_Enum.GreetInterfaceSerializeClass:
                    {
                        var dataClass = _reader_.Read<Rpc.Test.Interface.InterfaceSerializeClass>();
                        var _result_ = await (session as IGreeterRpc).GreetInterfaceSerializeClass(dataClass);
                        _writer_.Write<Rpc.Test.Interface.InterfaceSerializeClass>(_result_);
                    }
                    break;
                case IGreeterRpc_Enum.SessionParameter:
                    {
                        
                        var _result_ = await (session as IGreeterRpc).SessionParameter(session);
                        _writer_.Write(_result_);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }
}

#endregion
#region EuNet.Rpc.Test.Interface.IGreeterViewRpc
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_ANDROID || UNITY_IOS

namespace EuNet.Rpc.Test.Interface
{
    public interface IGreeterViewRpc_NoReply
    {
        void Greet(int value);
    }

    public enum IGreeterViewRpc_Enum : int
    {
        Greet = -1153730677,
    }

    public class GreeterViewRpc : RpcRequester, IGreeterViewRpc, IGreeterViewRpc_NoReply
    {
        public override Type InterfaceType => typeof(IGreeterViewRpc);

        public GreeterViewRpc(NetView view, TimeSpan? timeout = null)
            	: base(NetP2pUnity.Instance.Client, new NetViewRequestWaiter(view), timeout)
        {
        }

        public GreeterViewRpc(ISession target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IGreeterViewRpc_NoReply WithNoReply()
        {
            return this;
        }

        public GreeterViewRpc WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GreeterViewRpc(Target, requestWaiter, Timeout);
        }

        public GreeterViewRpc WithTimeout(TimeSpan? timeout)
        {
            return new GreeterViewRpc(Target, RequestWaiter, timeout);
        }

        public async Task<bool> Greet(int value)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterViewRpc_Enum.Greet);
                _writer_.Write(value);
                using(var _reader_ = await SendRequestAndReceive(_writer_))
                {
                    return _reader_.ReadBoolean();
                }
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void IGreeterViewRpc_NoReply.Greet(int value)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IGreeterViewRpc_Enum.Greet);
                _writer_.Write(value);
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }
    }

    [RequireComponent(typeof(NetView))]
    public abstract class GreeterViewRpcServiceBehaviour : MonoBehaviour, IRpcInvokable, IGreeterViewRpc
    {
        public abstract Task<bool> Greet(int value);
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            ISession session = _target_ as ISession;
            var typeEnum = (IGreeterViewRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case IGreeterViewRpc_Enum.Greet:
                    {
                        var value = _reader_.ReadInt32();
                        var _result_ = await Greet(value);
                        _writer_.Write(_result_);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }

    public class GreeterViewRpcServiceView : IRpcInvokable
    {
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            NetView _view_ = _target_ as NetView;
            var typeEnum = (IGreeterViewRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case IGreeterViewRpc_Enum.Greet:
                    {
                        var value = _reader_.ReadInt32();
                        var _result_ = await _view_.FindRpcHandler<IGreeterViewRpc>().Greet(value);
                        _writer_.Write(_result_);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }
}

#endif
#endregion
#region Rpc.Test.Interface.DataClass

namespace Rpc.Test.Interface
{
    public sealed class DataClassFormatter : INetDataFormatter<DataClass>
    {
        public static readonly DataClassFormatter Instance = new DataClassFormatter();

        public void Serialize(NetDataWriter _writer_, DataClass _value_, NetDataSerializerOptions options)
        {
            _writer_.Write(_value_.String);
            _writer_.Write(_value_.Property);
            _writer_.Write(_value_.Int);
        }

        public DataClass Deserialize(NetDataReader _reader_, NetDataSerializerOptions options)
        {
            var __String = _reader_.ReadString();
            var __Property = _reader_.ReadInt32();
            var __Int = _reader_.ReadInt32();

            return new DataClass() {
                String = __String,
                Property = __Property,
                Int = __Int,
            };
        }
    }
}

#endregion
#region Rpc.Test.Interface.DataStruct

namespace Rpc.Test.Interface
{
    public sealed class DataStructFormatter : INetDataFormatter<DataStruct>
    {
        public static readonly DataStructFormatter Instance = new DataStructFormatter();

        public void Serialize(NetDataWriter _writer_, DataStruct _value_, NetDataSerializerOptions options)
        {
            _writer_.Write(_value_.String);
            _writer_.Write(_value_.Property);
            _writer_.Write(_value_.Int);
        }

        public DataStruct Deserialize(NetDataReader _reader_, NetDataSerializerOptions options)
        {
            var __String = _reader_.ReadString();
            var __Property = _reader_.ReadInt32();
            var __Int = _reader_.ReadInt32();

            return new DataStruct() {
                String = __String,
                Property = __Property,
                Int = __Int,
            };
        }
    }
}

#endregion
#region Rpc.Test.Interface.GenericDataClass<T>

namespace Rpc.Test.Interface
{
    public sealed class GenericDataClassFormatter<T> : INetDataFormatter<GenericDataClass<T>>
    {
        public void Serialize(NetDataWriter _writer_, GenericDataClass<T> _value_, NetDataSerializerOptions options)
        {
            NetDataSerializer.Serialize<T>(_writer_, _value_.GenericValue);
        }

        public GenericDataClass<T> Deserialize(NetDataReader _reader_, NetDataSerializerOptions options)
        {
            var __GenericValue = NetDataSerializer.Deserialize<T>(_reader_);

            return new GenericDataClass<T>() {
                GenericValue = __GenericValue,
            };
        }
    }
}

#endregion
#region Rpc.Test.Interface.GenericDataStruct<T>

namespace Rpc.Test.Interface
{
    public sealed class GenericDataStructFormatter<T> : INetDataFormatter<GenericDataStruct<T>>
    {
        public void Serialize(NetDataWriter _writer_, GenericDataStruct<T> _value_, NetDataSerializerOptions options)
        {
            NetDataSerializer.Serialize<T>(_writer_, _value_.GenericValue);
        }

        public GenericDataStruct<T> Deserialize(NetDataReader _reader_, NetDataSerializerOptions options)
        {
            var __GenericValue = NetDataSerializer.Deserialize<T>(_reader_);

            return new GenericDataStruct<T>() {
                GenericValue = __GenericValue,
            };
        }
    }
}

#endregion
#region EuNet.Rpc.Test.Interface.Resolvers

namespace EuNet.Rpc.Test.Interface.Resolvers
{
    public sealed class GeneratedResolver : INetDataFormatterResolver
    {
        public static readonly GeneratedResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public INetDataFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            public static readonly INetDataFormatter<T> Formatter;

            static FormatterCache()
            {
                Formatter = (INetDataFormatter<T>)GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly Dictionary<Type, object> FormatterMap = new Dictionary<Type, object>() {
            { typeof(DataClass) , DataClassFormatter.Instance },
            { typeof(DataStruct) , DataStructFormatter.Instance },
            { typeof(GenericDataClass<>) , typeof(GenericDataClassFormatter<>) },
            { typeof(GenericDataStruct<>) , typeof(GenericDataStructFormatter<>) },
        };
        internal static object GetFormatter(Type t)
        {
            TypeInfo ti = t.GetTypeInfo();
            if (ti.IsGenericType)
            {
                Type genericType = ti.GetGenericTypeDefinition();
                object formatterType;
                if (FormatterMap.TryGetValue(genericType, out formatterType))
                {
                    return Activator.CreateInstance(((Type)formatterType).MakeGenericType(ti.GenericTypeArguments));
                }
            }

            else
            {
                object formatter;
                if (FormatterMap.TryGetValue(t, out formatter))
                {
                    return formatter;
                }
            }

            return null;
        }
    }
}

#endregion
