// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EuNet.CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using EuNet.Core;
using EuNet.Rpc;
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_ANDROID || UNITY_IOS
using EuNet.Unity;
using UnityEngine;
#endif
using SampleGameCommon;

#region SampleGameCommon.ILoginRpc

namespace SampleGameCommon
{
    public interface ILoginRpc_NoReply
    {
        void GetUserInfo();
        void Login(string id, EuNet.Core.ISession session);
    }

    public enum ILoginRpc_Enum : int
    {
        GetUserInfo = -1155460313,
        Login = -1327137735,
    }

    public class LoginRpc : RpcRequester, ILoginRpc, ILoginRpc_NoReply
    {
        public override Type InterfaceType => typeof(ILoginRpc);

        public LoginRpc() : base(null)
        {
        }

        public LoginRpc(ISession target) : base(target)
        {
        }

        public LoginRpc(ISession target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public ILoginRpc_NoReply WithNoReply()
        {
            return this;
        }

        public LoginRpc WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new LoginRpc(Target, requestWaiter, Timeout);
        }

        public LoginRpc WithTimeout(TimeSpan? timeout)
        {
            return new LoginRpc(Target, RequestWaiter, timeout);
        }

        public async Task<SampleGameCommon.UserInfo> GetUserInfo()
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)ILoginRpc_Enum.GetUserInfo);
                using(var _reader_ = await SendRequestAndReceive(_writer_))
                {
                    return _reader_.Read<SampleGameCommon.UserInfo>();
                }
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        public async Task<int> Login(string id, EuNet.Core.ISession session)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)ILoginRpc_Enum.Login);
                _writer_.Write(id);
                
                using(var _reader_ = await SendRequestAndReceive(_writer_))
                {
                    return _reader_.ReadInt32();
                }
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void ILoginRpc_NoReply.GetUserInfo()
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)ILoginRpc_Enum.GetUserInfo);
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void ILoginRpc_NoReply.Login(string id, EuNet.Core.ISession session)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)ILoginRpc_Enum.Login);
                _writer_.Write(id);
                
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }
    }

    public abstract class LoginRpcServiceAbstract : IRpcInvokable, ILoginRpc
    {
        public abstract Task<SampleGameCommon.UserInfo> GetUserInfo();
        public abstract Task<int> Login(string id, EuNet.Core.ISession session);
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            ISession session = _target_ as ISession;
            var typeEnum = (ILoginRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case ILoginRpc_Enum.GetUserInfo:
                    {
                        var _result_ = await GetUserInfo();
                        _writer_.Write<SampleGameCommon.UserInfo>(_result_);
                    }
                    break;
                case ILoginRpc_Enum.Login:
                    {
                        var id = _reader_.ReadString();
                        
                        var _result_ = await Login(id, session);
                        _writer_.Write(_result_);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }

    public class LoginRpcServiceSession : IRpcInvokable
    {
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            ISession session = _target_ as ISession;
            var typeEnum = (ILoginRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case ILoginRpc_Enum.GetUserInfo:
                    {
                        var _result_ = await (session as ILoginRpc).GetUserInfo();
                        _writer_.Write<SampleGameCommon.UserInfo>(_result_);
                    }
                    break;
                case ILoginRpc_Enum.Login:
                    {
                        var id = _reader_.ReadString();
                        
                        var _result_ = await (session as ILoginRpc).Login(id, session);
                        _writer_.Write(_result_);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }
}

#endregion
#region SampleGameCommon.IPlayerViewRpc
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_ANDROID || UNITY_IOS

namespace SampleGameCommon
{
    public interface IPlayerViewRpc_NoReply
    {
        void OnAttack();
        void OnSkill(byte index);
    }

    public enum IPlayerViewRpc_Enum : int
    {
        OnAttack = -1308402450,
        OnSkill = -1297090073,
    }

    public class PlayerViewRpc : RpcRequester, IPlayerViewRpc, IPlayerViewRpc_NoReply
    {
        public override Type InterfaceType => typeof(IPlayerViewRpc);

        public PlayerViewRpc(NetView view, DeliveryMethod deliveryMethod, TimeSpan? timeout = null)
            	: base(NetP2pUnity.Instance.Client, new NetViewRequestWaiter(view, deliveryMethod), timeout)
        {
        }

        public PlayerViewRpc(ISession target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IPlayerViewRpc_NoReply WithNoReply()
        {
            return this;
        }

        public PlayerViewRpc WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new PlayerViewRpc(Target, requestWaiter, Timeout);
        }

        public PlayerViewRpc WithTimeout(TimeSpan? timeout)
        {
            return new PlayerViewRpc(Target, RequestWaiter, timeout);
        }

        public async Task OnAttack()
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IPlayerViewRpc_Enum.OnAttack);
                await SendRequestAndWait(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        public async Task OnSkill(byte index)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IPlayerViewRpc_Enum.OnSkill);
                _writer_.Write(index);
                await SendRequestAndWait(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void IPlayerViewRpc_NoReply.OnAttack()
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IPlayerViewRpc_Enum.OnAttack);
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }

        void IPlayerViewRpc_NoReply.OnSkill(byte index)
        {
            var _writer_ = NetPool.DataWriterPool.Alloc();
            try
            {
                _writer_.Write((int)IPlayerViewRpc_Enum.OnSkill);
                _writer_.Write(index);
                SendRequest(_writer_);
            }
            finally
            {
                NetPool.DataWriterPool.Free(_writer_);
            }
        }
    }

    [RequireComponent(typeof(NetView))]
    public abstract class PlayerViewRpcServiceBehaviour : MonoBehaviour, IRpcInvokable, IPlayerViewRpc
    {
        public abstract Task OnAttack();
        public abstract Task OnSkill(byte index);
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            ISession session = _target_ as ISession;
            var typeEnum = (IPlayerViewRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case IPlayerViewRpc_Enum.OnAttack:
                    {
                        await OnAttack();
                    }
                    break;
                case IPlayerViewRpc_Enum.OnSkill:
                    {
                        var index = _reader_.ReadByte();
                        await OnSkill(index);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }

    public class PlayerViewRpcServiceView : IRpcInvokable
    {
        public async Task<bool> Invoke(object _target_, NetDataReader _reader_, NetDataWriter _writer_)
        {
            NetView _view_ = _target_ as NetView;
            var typeEnum = (IPlayerViewRpc_Enum)_reader_.ReadInt32();
            switch(typeEnum)
            {
                case IPlayerViewRpc_Enum.OnAttack:
                    {
                        await _view_.FindRpcHandler<IPlayerViewRpc>().OnAttack();
                    }
                    break;
                case IPlayerViewRpc_Enum.OnSkill:
                    {
                        var index = _reader_.ReadByte();
                        await _view_.FindRpcHandler<IPlayerViewRpc>().OnSkill(index);
                    }
                    break;
                default: return false;
            }

            return true;
        }
    }
}

#endif
#endregion
#region SampleGameCommon.GenericClass<T>

namespace SampleGameCommon
{
    public sealed class GenericClassFormatter<T> : INetDataFormatter<GenericClass<T>>
    {
        public void Serialize(NetDataWriter _writer_, GenericClass<T> _value_, NetDataSerializerOptions options)
        {
            NetDataSerializer.Serialize<T>(_writer_, _value_.SlotId);
        }

        public GenericClass<T> Deserialize(NetDataReader _reader_, NetDataSerializerOptions options)
        {
            var __SlotId = NetDataSerializer.Deserialize<T>(_reader_);

            return new GenericClass<T>() {
                SlotId = __SlotId,
            };
        }
    }
}

#endregion
#region SampleGameCommon.RoomInfo

namespace SampleGameCommon
{
    public sealed class RoomInfoFormatter : INetDataFormatter<RoomInfo>
    {
        public static readonly RoomInfoFormatter Instance = new RoomInfoFormatter();

        public void Serialize(NetDataWriter _writer_, RoomInfo _value_, NetDataSerializerOptions options)
        {
            _writer_.Write(_value_.Name);
            NetDataSerializer.Serialize<SampleGameCommon.RoomSlotInfo[]>(_writer_, _value_.Slots);
            _writer_.Write(_value_.Id);
        }

        public RoomInfo Deserialize(NetDataReader _reader_, NetDataSerializerOptions options)
        {
            var __Name = _reader_.ReadString();
            var __Slots = NetDataSerializer.Deserialize<SampleGameCommon.RoomSlotInfo[]>(_reader_);
            var __Id = _reader_.ReadInt32();

            return new RoomInfo() {
                Name = __Name,
                Slots = __Slots,
                Id = __Id,
            };
        }
    }
}

#endregion
#region SampleGameCommon.RoomSlotInfo

namespace SampleGameCommon
{
    public sealed class RoomSlotInfoFormatter : INetDataFormatter<RoomSlotInfo>
    {
        public static readonly RoomSlotInfoFormatter Instance = new RoomSlotInfoFormatter();

        public void Serialize(NetDataWriter _writer_, RoomSlotInfo _value_, NetDataSerializerOptions options)
        {
            _writer_.Write(_value_.SlotId);
        }

        public RoomSlotInfo Deserialize(NetDataReader _reader_, NetDataSerializerOptions options)
        {
            var __SlotId = _reader_.ReadInt32();

            return new RoomSlotInfo() {
                SlotId = __SlotId,
            };
        }
    }
}

#endregion
#region SampleGameCommon.Resolvers

namespace SampleGameCommon.Resolvers
{
    public sealed class GeneratedResolver : INetDataFormatterResolver
    {
        public static readonly GeneratedResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public INetDataFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            public static readonly INetDataFormatter<T> Formatter;

            static FormatterCache()
            {
                Formatter = (INetDataFormatter<T>)GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly Dictionary<Type, object> FormatterMap = new Dictionary<Type, object>() {
            { typeof(GenericClass<>) , typeof(GenericClassFormatter<>) },
            { typeof(RoomInfo) , RoomInfoFormatter.Instance },
            { typeof(RoomSlotInfo) , RoomSlotInfoFormatter.Instance },
        };
        internal static object GetFormatter(Type t)
        {
            TypeInfo ti = t.GetTypeInfo();
            if (ti.IsGenericType)
            {
                Type genericType = ti.GetGenericTypeDefinition();
                object formatterType;
                if (FormatterMap.TryGetValue(genericType, out formatterType))
                {
                    return Activator.CreateInstance(((Type)formatterType).MakeGenericType(ti.GenericTypeArguments));
                }
            }

            else
            {
                object formatter;
                if (FormatterMap.TryGetValue(t, out formatter))
                {
                    return formatter;
                }
            }

            return null;
        }
    }
}

#endregion
